"""Contract test: GET /v1/forecasts (T058, US4, FR-006, FR-007).

No POST-creation endpoint exists per the OpenAPI contract; forecasts are generated by
`ForecastingEngine` (batch/internal) and seeded via the repository here, mirroring the
established `test_replenishment.py` pattern for domains without a public creation API.
"""

from __future__ import annotations

from datetime import date

from src.domain.forecasting.models import DemandForecastRepository, ForecastErrorIndicator


def test_list_forecasts_empty(client):
    response = client.get("/v1/forecasts")
    assert response.status_code == 200
    assert response.json() == []


def test_list_forecasts_filters_by_sku_and_location(client, db_session):
    repo = DemandForecastRepository(db_session)
    repo.create(
        sku_id="SKU-1",
        location_id="STORE-1",
        period_start=date(2025, 1, 1),
        period_end=date(2025, 1, 7),
        forecast_quantity=42.0,
        trend_factor=1.1,
        seasonality_factor=1.0,
        promotion_factor=1.0,
        history_points_used=5,
        error_indicator=ForecastErrorIndicator.LOW,
        factors={"history": [10, 12, 14, 16, 18]},
        narration="test narration",
    )
    repo.create(
        sku_id="SKU-2",
        location_id="STORE-2",
        period_start=date(2025, 1, 1),
        period_end=date(2025, 1, 7),
        forecast_quantity=10.0,
        trend_factor=1.0,
        seasonality_factor=1.0,
        promotion_factor=1.0,
        history_points_used=1,
        error_indicator=ForecastErrorIndicator.INSUFFICIENT_HISTORY,
        factors={"history": [10]},
        narration=None,
    )
    db_session.commit()

    response = client.get("/v1/forecasts", params={"sku_id": "SKU-1"})
    assert response.status_code == 200
    body = response.json()
    assert len(body) == 1
    assert body[0]["sku_id"] == "SKU-1"
    assert body[0]["error_indicator"] == "low"

    response = client.get("/v1/forecasts", params={"location_id": "STORE-2"})
    assert response.status_code == 200
    body = response.json()
    assert len(body) == 1
    assert body[0]["error_indicator"] == "insufficient_history"
